version: "3.8"
services:
  real-estate-ml:
    image: real-estate-ml:latest
    expose: 
      - 8000
    volumes:
      - real-estate-ml-logs:/var/log/real-estate-ml
  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - real-estate-ml
    ports:
      - "8001:8001"      
volumes:
  real-estate-ml-logs: